run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - gocritic
    - unconvert
    - ineffassign
    - staticcheck
    - prealloc
    - nilerr
    - gosimple
    - asasalint
    - canonicalheader
    - perfsprint
    - predeclared
    - asciicheck
    - bidichk
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - goheader
    - goprintffuncname
    - grouper
    - iface
    - importas
    - interfacebloat
    - intrange
    - mirror
    - nonamedreturns
    - nosprintfhostport
    - reassign
    - unparam
    - usestdlibvars
    - wastedassign
  disable:
    - errcheck

issues:
  exclude-use-default: false
