services:
  govd-bot:
    image: govdbot/govd:main
    container_name: govd-bot
    restart: unless-stopped
    networks:
      - govd-network
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./cookies:/app/cookies
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: govd
      MARIADB_USER: govd
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
    networks:
      - govd-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "govd", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db:

networks:
  govd-network:
    driver: bridge

